# Form implementation generated from reading ui file 'gui_final_plant_new.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 331)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 45, 71, 21))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 20, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.sensor_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sensor_button.setGeometry(QtCore.QRect(54, 100, 251, 23))
        self.sensor_button.setObjectName("sensor_button")
        self.moisture_display = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.moisture_display.setGeometry(QtCore.QRect(150, 160, 64, 23))
        self.moisture_display.setObjectName("moisture_display")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 141, 20))
        self.label_4.setObjectName("label_4")
        self.needs_water_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.needs_water_label.setGeometry(QtCore.QRect(150, 200, 121, 20))
        self.needs_water_label.setObjectName("needs_water_label")
        self.ok_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ok_label.setGeometry(QtCore.QRect(150, 220, 91, 20))
        self.ok_label.setObjectName("ok_label")
        self.water_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.water_button.setGeometry(QtCore.QRect(60, 250, 241, 23))
        self.water_button.setObjectName("water_button")
        self.plant_select = QtWidgets.QComboBox(parent=self.centralwidget)
        self.plant_select.setGeometry(QtCore.QRect(59, 70, 241, 22))
        self.plant_select.setObjectName("plant_select")
        self.plant_select.addItem("")
        self.plant_select.addItem("")
        self.plant_select.addItem("")
        self.plant_select.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Plant Watering Tracker"))
        self.label_2.setText(_translate("MainWindow", "Select Plant:"))
        self.sensor_button.setText(_translate("MainWindow", "Read Sensor"))
        self.label_4.setText(_translate("MainWindow", "Current Moisture Level"))
        self.needs_water_label.setText(_translate("MainWindow", "Needs Water!"))
        self.ok_label.setText(_translate("MainWindow", "Plant is OK!"))
        self.water_button.setText(_translate("MainWindow", "Water Plant"))
        self.plant_select.setItemText(0, _translate("MainWindow", "Cactus"))
        self.plant_select.setItemText(1, _translate("MainWindow", "Rose"))
        self.plant_select.setItemText(2, _translate("MainWindow", "Sunflower"))
        self.plant_select.setItemText(3, _translate("MainWindow", "Aloe Vera"))
